customCommands:
  - key: '<f1>'
    context: 'files'
    command: "git difftool --tool bc --dir-diff --no-symlinks"

  - key: '<f5>'
    command: 'git fetch --prune'
    context: 'localBranches'
    stream: true
